print("Hello Git")
print("Hello brothor")
print("Hello sister")
print("Hello Lucy")
print("Hello Join")
print("Hello Git")
print("Hello Git")
print("Hello Git")
print("Hello Git")
print("Hello Git")
print("Hello Git")
print("Hello Git")
print("Hello Git")
print("Hello Git")
print("Hello Git")
print("Hello Git")
print("这是新的")
